repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: check-json
  - id: pretty-format-json
    args: ['--autofix', '--no-sort-keys']
- repo: https://github.com/standard/standard
  rev: v16.0.3
  hooks:
  - id: standard
